### ISSUE TITLE
Lateral bar is shown in the final PDF

### ISSUE THREAD

**Issue by moshpirit** [tobiasBora/Scribd-downloader#5]
I don't know if it's related with #3 but I got this: 
![d](https://cloud.githubusercontent.com/assets/7888062/18808533/b595d48c-825c-11e6-8f9b-d388b31ad344.png)

**Comment by tobiasBora** [comment]
Hello,

Yes, I know the script is buggy, I would like to update it, but since I'm a bit overbooked these days I don't when I'll take the time to update it. It shouldn't be long to do however, so I may correct it soon…

Le 24 septembre 2016 14:44:09 GMT+02:00, moshpirit notifications@github.com a écrit :

> I don't know if it's related with #3 but I got this: 
> ![d](https://cloud.githubusercontent.com/assets/7888062/18808533/b595d48c-825c-11e6-8f9b-d388b31ad344.png)
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tobiasBora/Scribd-downloader/issues/5

## 

TobiasBora

**Comment by moshpirit** [comment]
Good!! Thanks a lot!!

**Comment by tobiasBora** [comment]
Hello,
I've some news. I won't support anymore this repository, but I created a new one here: https://github.com/tobiasBora/scribd-downloader-3 . For now, I just found one document that is buggy and I'll try to solve it, but else it works pretty nicefully.
